### ISSUE TITLE
Clickable text 

### ISSUE THREAD

**Issue by Excalibur2019mx** [cmaybon/Wox.Plugin.FindText#1]
I have been looking for a way to use the mouse less and found the programs out there don't do something your program, slightly modified, could do: the user types in a few characters and if matched then the program clicks on it (instead of using the mouse). If there are many instances on the screen, show boxes (like your program does) with numbers and the user types the number he wants to be programmatically clicked. Would you mind adding this probably as a fork? I read your code and it is amazing yet I am not at the level of knowing how to add this

**Comment by cmaybon** [comment]
For web browsing you could use the extension [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en). Is that the style of functionality your looking to be added?
If so, yeah I could add something similar.

**Comment by Excalibur2019mx** [comment]
Thank you. Yes, that is the functionality I am looking for both for anything in windows!

**Comment by cmaybon** [comment]
Added in v1.1.0 (it is also updated on the Wox plugin list).
Note you'll need to install the `pyautogui` python package.

![preview_mouse_click](https://user-images.githubusercontent.com/41503372/152612744-7a1ad25c-afa5-4803-bc4f-270519f4fae2.gif)

**Comment by Excalibur2019mx** [comment]
You are very gentle! I installed all components and tested pytesseract from py prompt but it's just doing nothing, Wox shows the same legends as you show in the animation but then nothing. I will keep debugging

**Comment by cmaybon** [comment]
The best way I've found to test Wox plugins (written in python) is to copy `wox.py` to the plugin directory and run the plugin using whatever python install you've set Wox to use.

In Wox's settings go `Plugin > FindText > Plugin Directory` and [save this file there (make sure to name it `wox.py`)](https://raw.githubusercontent.com/Wox-launcher/Wox/master/JsonRPC/wox.py).
So you directory looks like this:
![image](https://user-images.githubusercontent.com/41503372/152663041-1d814426-f832-4902-8180-8e884c8e9d77.png)

Then run `main.py` via a terminal using the python that is specified here:
Open Wox's `settings > General > Python Directory`.
This was you can see any exceptions occuring and will make debugging much easier.

(Remeber to delete `wox.py` from the plugin directory when you are done testing.)

**Comment by Excalibur2019mx** [comment]
I apologize, I was sick and could not test much but recently. It is now
runnning, thank you vm! but the search is very slow. I wonder if some %
accuracy could be used as to make it faster
